version: "3.8"

services:
  bot:
    build: .
    container_name: social-media-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/usr/src/app/downloads
